# Generated by Django 2.2 on 2019-07-21 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190721_1515'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Adreslerim'},
        ),
    ]
